# -*- coding: utf-8 -*-
"""Despliegue_SC4701_Streamlit(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSFMQRIEk-vaZ6if0m0pNcQJrQxmHESi
"""

#Importamos librerías básicas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Cargar modelo
import pickle
#filename = '/content/drive/MyDrive/Colab Notebooks/modelo-class.pkl'
filename = 'modelo-class2.pkl'
modelTree, labelencoder,variables = pickle.load(open(filename, 'rb'))

#Interfaz grafica
import streamlit as st
st.title('Predicción Fuga Sellos SC4701')
Flujo=st.slider ('FI_47012', min_value=80, max_value=150,value=90,step=5)
Presion_Succion=st.slider ('PI_47031', min_value=0, max_value=700,value=680,step=20)
Presion_Descarga=st.slider ('PI_47033', min_value=0, max_value=1000,value=920,step=20)
Temperatura_Succion=st.slider ('TI_47042', min_value=0, max_value=200,value=140,step=20)
Temperatura_Descarga=st.slider ('TI_47043', min_value=0, max_value=360,value=240,step=20)
Corriente_Motor=st.slider ('MUC_47018A', min_value=0, max_value=400,value=280,step=20)
Vibracion_Compresor=st.slider ('VYT_47302', min_value=0.0, max_value=6.0,value=0.4,step=0.1)

#DataFrame
datos=[[Flujo, Presion_Succion, Presion_Descarga, Temperatura_Succion,Temperatura_Descarga, Corriente_Motor, Vibracion_Compresor]]
data=pd.DataFrame(datos,columns=[Flujo, Presion_Succion, Presion_Descarga, Temperatura_Succion,Temperatura_Descarga, Corriente_Motor, Vibracion_Compresor])

#Prediccion
Y_Pred=modelTree.predict(data)
print(Y_Pred)

data['Prediccion']=Y_Pred
data.head()

data